import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./global.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";

import GlobalContextWrapper from "@/contexts/GlobalContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Basic Chat App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AntdRegistry>
          <GlobalContextWrapper>{children}</GlobalContextWrapper>
        </AntdRegistry>
      </body>
    </html>
  );
}
